apiVersion: v1
kind: Secret
metadata:
  name: streamshield-postgres-secret
  namespace: streamshield
type: Opaque
stringData:
  POSTGRES_USER: streamshield_admin
  POSTGRES_PASSWORD: streamshield_password